---
settings:
  name: ONTAP FlexArray
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti ONTAP FlexArray
    url: "/index.html"
  - section: implement-e-series
  - section: implement-third-party
  - section: install
  - title: Note legali
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
