---
permalink: install/concept_using_lun_groups_to_partition_the_load_over_v_series_connections.html 
sidebar: sidebar 
keywords: benefits, use, multiple, lun, groups 
summary: È possibile utilizzare più gruppi di LUN nella configurazione dello storage per ottenere capacità aggiuntiva e migliorare le performance di sistema distribuendo il carico di lavoro su più porte di destinazione. 
---
= Vantaggi dell'utilizzo di più gruppi di LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare più gruppi di LUN nella configurazione dello storage per ottenere capacità aggiuntiva e migliorare le performance di sistema distribuendo il carico di lavoro su più porte di destinazione.

Un _gruppo LUN_ è un insieme di dispositivi logici sull'array di archiviazione a cui un sistema ONTAP accede tramite gli stessi percorsi. L'amministratore dell'array di storage configura una serie di dispositivi logici come un gruppo per definire quali WWPN dell'host possono accedervi. ONTAP fa riferimento a questo insieme di dispositivi come _gruppo LUN_.

I vantaggi dell'utilizzo di più gruppi di LUN sono i seguenti:

* Esistono limiti al numero di LUN supportati da una coppia di porte FC Initiator.
+
In particolare, per gli array di storage di grandi dimensioni la capacità richiesta potrebbe superare quella che un singolo gruppo LUN può fornire. Pertanto, l'utilizzo di più gruppi di LUN può essere vantaggioso.

* È possibile suddividere il carico di array LUN in partizioni sulle coppie di porte dell'iniziatore FC.


[NOTE]
====
L'utilizzo di più gruppi LUN non è supportato per tutti gli array di storage. Consulta _Interoperability Matrix_ per determinare se per il tuo storage array è supportata una configurazione che utilizza più gruppi di LUN.

====
*Informazioni correlate*

https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]
