---
permalink: install/task_verifying_if_the_back_end_configuration_matches_the_expected_output.html 
sidebar: sidebar 
keywords: verify, back-end, configuration, matches, intended, configuration 
summary: Dopo aver risolto gli errori di configurazione back-end rilevati dagli errori di archiviazione, è necessario controllare se la configurazione back-end esistente corrisponde alla configurazione desiderata e risolvere i problemi derivanti da eventuali discrepanze. 
---
= Verificare che la configurazione back-end corrisponda alla configurazione prevista
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver risolto gli errori di configurazione back-end rilevati da `storage errors show`, è necessario controllare se la configurazione back-end esistente corrisponde alla configurazione desiderata e risolvere i problemi derivanti da eventuali discrepanze.

.Fasi
. Immettere il seguente comando: `storage array config show`
+
L' `storage array config show` output raggruppa informazioni sui gruppi di LUN, sul numero di LUN e sul percorso per array di storage, come dimostra il seguente esempio per una coppia ha:

+
[listing]
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count  Array Name      Array Target Port   Initiator
------------ ----- ----- ---------------  ------------------  ---------
mysystem1a    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
mysystem1b    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
8 entries were displayed.
----
. Verificare l' `storage array config show` output di ogni segnalazione di problema nella tabella seguente e fare riferimento alle informazioni appropriate per la soluzione.
+
|===
| Se si trova questo problema... | Vedi queste informazioni... 


 a| 
Gruppi LUN vuoti
 a| 
xref:reference_reasons_for_no_luns_in_the_array_lun_group.adoc[Motivi dell'assenza di LUN nel gruppo di array LUN]



 a| 
Storage array previsti mancanti
 a| 
xref:reference_reasons_storage_arrays_are_missing_from_command_output.adoc[Motivi per cui potresti non vedere tutti gli storage array previsti]



 a| 
Più gruppi di array LUN del previsto
 a| 
xref:reference_reasons_for_more_array_lun_groups_than_expected.adoc[Motivi per utilizzare più gruppi di array LUN del previsto]



 a| 
Numero di gruppi di array LUN inferiore al previsto
 a| 
xref:reference_reasons_for_fewer_array_lun_groups_than_expected.adoc[Motivi per scegliere un numero inferiore di gruppi di array LUN rispetto al previsto]



 a| 
I gruppi di array LUN non mostrano il numero di LUN previsto
 a| 
xref:reference_reasons_for_the_incorrect_number_of_luns_in_array_lun_groups.adoc[Motivi per il numero errato di LUN nei gruppi di array LUN]



 a| 
Meno percorsi del previsto
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Meno di due percorsi a un array LUN]



 a| 
Più percorsi del previsto
 a| 
xref:reference_reasons_for_more_paths_to_an_array_lun_than_expected.adoc[Motivi per creare un numero maggiore di percorsi a un array LUN rispetto al previsto]

|===

