---
permalink: install/task_assigning_ownership_of_array_luns.html 
sidebar: sidebar 
keywords: assign, ownership, array, luns 
summary: Su un sistema ONTAP in cui il volume root si trova su shelf di dischi, è necessario assegnare la proprietà di array LUN a un nodo prima di aggiungerli a un aggregato per utilizzarli come storage. 
---
= Assegnazione della proprietà delle LUN degli array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Su un sistema ONTAP in cui il volume root si trova su shelf di dischi, è necessario assegnare la proprietà di array LUN a un nodo prima di aggiungerli a un aggregato per utilizzarli come storage.

*Cosa ti serve*

* Il test della configurazione back-end (test della connettività e della configurazione dei dispositivi dietro i sistemi ONTAP) deve essere completato.
* I LUN degli array che si desidera assegnare devono essere presentati ai sistemi ONTAP.


È possibile assegnare la proprietà di LUN array con le seguenti caratteristiche:

* Non sono di proprietà.
* Non presentano errori di configurazione degli array di storage, come ad esempio:
+
** Il LUN dell'array è inferiore o superiore alle dimensioni supportate da ONTAP.
** LDEV è mappato su una sola porta.
** All'LDEV sono assegnati ID LUN non coerenti.
** Il LUN è disponibile su un solo percorso.




ONTAP genera un messaggio di errore se si tenta di assegnare la proprietà di un LUN dell'array con errori di configurazione back-end che interferirebbero con il sistema ONTAP e l'array di storage che funzionano insieme. È necessario correggere tali errori prima di procedere con l'assegnazione del LUN dell'array.

ONTAP avvisa l'utente se si tenta di assegnare un LUN di array con un errore di ridondanza: Ad esempio, tutti i percorsi a questo LUN di array sono collegati allo stesso controller o solo a un percorso del LUN di array. È possibile correggere un errore di ridondanza prima o dopo l'assegnazione della proprietà del LUN.

.Fasi
. Immettere il seguente comando per visualizzare i LUN dell'array non ancora assegnati a un nodo:``storage disk show -container-type unassigned``
. Immettere il seguente comando per assegnare un array LUN a questo nodo:``storage disk assign -disk arrayLUNname -owner nodename``
+
Se si desidera correggere un errore di ridondanza dopo l'assegnazione del disco invece che prima, è necessario utilizzare il `-force` parametro con il `storage disk assign` comando.


