---
permalink: install/task_preparing_a_storage_array_for_use_with_ontap_systems.html 
sidebar: sidebar 
keywords: prepare, storage, array, use, ontap, systems 
summary: 'Prima di iniziare a configurare i sistemi ONTAP in una configurazione con LUN degli array, l"amministratore dello storage array deve preparare lo storage per l"utilizzo con ONTAP.' 
---
= Preparazione di uno storage array per l'utilizzo con i sistemi ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di iniziare a configurare i sistemi ONTAP in una configurazione con LUN degli array, l'amministratore dello storage array deve preparare lo storage per l'utilizzo con ONTAP.

*Cosa ti serve*

Gli array di storage, il firmware e gli switch che si intende utilizzare nella configurazione devono essere supportati dalla versione specifica di ONTAP.

* https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilità NetApp"]
+
In IMT, è possibile utilizzare il campo soluzione storage per selezionare la soluzione MetroCluster. Utilizzare *Esplora componenti* per selezionare i componenti e la versione di ONTAP per perfezionare la ricerca. È possibile fare clic su *Mostra risultati* per visualizzare l'elenco delle configurazioni supportate che corrispondono ai criteri.

* https://hwu.netapp.com["NetApp Hardware Universe"]


Per eseguire questa attività sull'array di storage, è necessario coordinarsi con l'amministratore dell'array di storage.

.Fasi
. Creare almeno quattro LUN sullo storage array affinché i sistemi ONTAP possano utilizzare.
+
Ciascun nodo della coppia ha richiede una LUN di array per il volume root e una LUN di array per i core dump.

. Configurare i parametri sull'array di storage necessari per lavorare con ONTAP.
+
** https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["Implementazione della virtualizzazione FlexArray per storage di terze parti"]
** https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["Implementazione della virtualizzazione FlexArray per lo storage NetApp e-Series"]



